### ISSUE TITLE
Image processing

### ISSUE THREAD

**Issue by Maximellerbach** [C-Sors-c/SudoC#13]
find a good way to handle images as arrays 
+ do some utils functions for IO and image manipulation

**Comment by mickael-btc** [comment]
bonsoir, yes

**Comment by mickael-btc** [comment]
- [x] save
- [x] load 
- [x] grayscale
- [x] gaussian blur
- [ ] canny
- [ ] line hough
- [ ] resize
- [ ] rotate
- [ ] translate
